#!/usr/bin/env python3
"""Do the token-level defenses suppress the teacher-proxy likelihood gap?

The sequence-level rule the defenses are up against scores a trace by

    v_gap(y) = log P_teacher(y) - log P_proxy(y)

and this script measures that quantity directly on traces already generated by
each defense, against the undefended teacher.

PoE samples each token from a blend of the two models,

    q(a|h) proportional to p_teacher(a|h)^(1-gamma) * p_proxy(a|h)^gamma

so it should pull the sampled text toward tokens the proxy also finds likely,
and v_gap should fall as gamma rises. Antidistillation sampling is measured the
same way at each lambda. It perturbs the teacher's logits with a
finite-difference penalty and never consults the proxy, so whatever it does to
v_gap is a side effect; comparing the two families says whether a drop is
attributable to the proxy mixing or to perturbing the traces at all.

v_gap is one number per trace, defined by the equation above. Because the sum
grows with trace length -- on these traces its rank correlation with response
length is +0.88 -- a bare sum would mostly report how long the traces are, and
PoE changes trace length as a side effect. Dividing by the number of response
tokens gives the same per-trace quantity on a per-token scale, comparable across
traces of different lengths, so that is the headline number. The sum is reported
alongside it, and the median per-token gap is reported too, since one trace with
an extreme gap cannot move a median.

Every source covers the identical GSM8K problems in the same order, so each
defense is compared to the undefended baseline *paired by problem*: the
statistic is the mean of v_gap(defended trace) - v_gap(standard trace) over
problems. Pairing cancels problem difficulty, which is the dominant source of
variation in v_gap, and it comes with a distribution-free companion, the
fraction of problems whose gap went down at all. Beyond the average, the report
gives the quantiles of each distribution, whether one sits wholly below the
other, and the largest distance between their CDFs.

Both models score token ids produced by the teacher's tokenizer, which is what
PoE does at generation time, and only response tokens count.

Usage:
    python scripts/vgap_by_gamma.py --seed 123
    python scripts/vgap_by_gamma.py --report-only
"""
from __future__ import annotations

import argparse
import json
import math
import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

_root = Path(__file__).resolve().parent.parent
for _path in (str(_root / "src"), str(_root / "scripts")):
    if _path not in sys.path:
        sys.path.insert(0, _path)

os.environ.setdefault("HF_HUB_DISABLE_PROGRESS_BARS", "1")
os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")

from rich.console import Console

from clean_sweep.config import FullConfig
from score_vgap import _free, _load_model, _percentile, build_examples, score_with_model

console = Console()

BASELINE = "standard"
# Ordered for the report: the baseline, then PoE by strength, then the other
# defense. Anything found on disk but not named here is appended.
PREFERRED_ORDER = [
    "standard",
    "poe_gamma_0.6",
    "poe_gamma_0.7",
    "antidistillation_lam_0.05",
    "antidistillation_lam_0.055",
]


def _mean(values: list[float]) -> float:
    return sum(values) / len(values) if values else float("nan")


def _stderr(values: list[float]) -> float:
    n = len(values)
    if n < 2:
        return float("nan")
    mu = _mean(values)
    return math.sqrt(sum((v - mu) ** 2 for v in values) / (n - 1) / n)


def _gamma_of(source: str) -> float | None:
    """The PoE mixing weight a source was generated with, if it is a PoE source."""
    if source == BASELINE:
        return 0.0
    if source.startswith("poe_gamma_"):
        try:
            return float(source.removeprefix("poe_gamma_"))
        except ValueError:
            return None
    return None


def _defense_of(source: str) -> tuple[str, str, float | None]:
    """The defense family a source came from, its knob name, and its setting.

    PoE and antidistillation sampling are both measured here as defenses in
    their own right. They also happen to answer different questions: PoE mixes
    the proxy into the sampling distribution and so should move v_gap directly,
    while ADS perturbs the teacher's logits without ever consulting the proxy,
    so whatever it does to v_gap is a side effect.
    """
    if source == BASELINE:
        return "none", "teacher", 0.0
    if source.startswith("poe_gamma_"):
        try:
            return "PoE", "gamma", float(source.removeprefix("poe_gamma_"))
        except ValueError:
            return "PoE", "gamma", None
    if source.startswith("antidistillation_lam_"):
        try:
            return "ADS", "lambda", float(source.removeprefix("antidistillation_lam_"))
        except ValueError:
            return "ADS", "lambda", None
    return "other", "setting", None


def discover_sources(input_dir: Path) -> list[str]:
    stems = {p.stem.removeprefix("train_") for p in input_dir.glob("train_*.json")}
    ordered = [s for s in PREFERRED_ORDER if s in stems]
    return ordered + sorted(stems - set(ordered))


def score_sources(
    sources: list[str],
    input_dir: Path,
    cfg: FullConfig,
    *,
    max_length: int,
    batch_size: int,
    row_chunk: int,
    seed: int,
    limit: int,
) -> dict[str, Any]:
    """Teacher and proxy log-probs for every trace of every source.

    Each model is loaded once and scores all sources before being freed, so peak
    memory is one model and the 7B is not paid for five times over.
    """
    import torch

    from transformers import AutoTokenizer
    from clean_sweep.generation.core import ensure_chat_template

    tokenizer = AutoTokenizer.from_pretrained(
        cfg.model.tokenizer or cfg.model.teacher,
        trust_remote_code=True,
    )
    tokenizer = ensure_chat_template(tokenizer)
    pad_id = tokenizer.pad_token_id
    if pad_id is None:
        pad_id = tokenizer.eos_token_id or 0

    examples_by_source: dict[str, list[dict[str, Any]]] = {}
    for source in sources:
        rows = json.loads((input_dir / f"train_{source}.json").read_text())
        if limit:
            rows = rows[:limit]
        examples = build_examples(rows, tokenizer, max_length)
        examples_by_source[source] = examples
        lengths = [ex["n_response_tokens"] for ex in examples]
        console.print(
            f"  {source}: {len(examples)} traces, "
            f"response tokens mean={_mean([float(v) for v in lengths]):.0f}, "
            f"max={max(lengths, default=0)}, "
            f"truncated={sum(ex['truncated'] for ex in examples)}"
        )

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    logprobs: dict[str, dict[str, list[float]]] = {s: {} for s in sources}
    clamped: dict[str, int] = {}

    for role, name in (("teacher", cfg.model.teacher), ("proxy", cfg.model.proxy_student)):
        console.print(f"\n  Loading {role} {name}")
        model = _load_model(name, cfg, device)
        total_clamped = 0
        for source in sources:
            values, n_clamped = score_with_model(
                model,
                examples_by_source[source],
                pad_id=pad_id,
                batch_size=batch_size,
                row_chunk=row_chunk,
                label=f"{role} {source}",
                shuffle_seed=seed,
            )
            logprobs[source][role] = values
            total_clamped += n_clamped
        clamped[role] = total_clamped
        _free(model)

    per_source: dict[str, list[dict[str, Any]]] = {}
    for source in sources:
        rows = []
        for ex, lt, lp in zip(
            examples_by_source[source],
            logprobs[source]["teacher"],
            logprobs[source]["proxy"],
        ):
            n_tokens = ex["n_response_tokens"]
            gap = lt - lp
            rows.append({
                "example_id": ex["example_id"],
                "n_response_tokens": n_tokens,
                "truncated": ex["truncated"],
                "correct": ex["correct"],
                "finite": math.isfinite(lt) and math.isfinite(lp) and n_tokens > 0,
                "logp_teacher": lt,
                "logp_proxy": lp,
                "vgap_sum": gap,
                "vgap_mean": gap / n_tokens if n_tokens else 0.0,
            })
        per_source[source] = rows

    return {"traces": per_source, "clamped": clamped}


# The whole distribution of per-trace v_gap, stored as a quantile grid so the
# report can draw a CDF and compare distributions without keeping every trace.
# 201 points resolves the curve to half a percentile, well past what is visible.
GRID = [i / 200 for i in range(201)]
# Dominance is judged over the interior: at the very ends the quantile function
# is one observation, and a lone outlier should not decide the verdict.
DOMINANCE_RANGE = (0.01, 0.99)
REPORT_QUANTILES = [0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95]


def _quantile_grid(values: list[float]) -> list[float]:
    ordered = sorted(values)
    if not ordered:
        return [float("nan")] * len(GRID)
    return [_percentile(ordered, q) for q in GRID]


def _usable(rows: list[dict[str, Any]], drop_truncated: bool) -> list[dict[str, Any]]:
    return [r for r in rows if r["finite"] and not (drop_truncated and r["truncated"])]


def summarize_source(rows: list[dict[str, Any]], drop_truncated: bool) -> dict[str, Any]:
    usable = _usable(rows, drop_truncated)
    means = [r["vgap_mean"] for r in usable]
    sums = [r["vgap_sum"] for r in usable]
    lengths = [float(r["n_response_tokens"]) for r in usable]
    return {
        "n": len(rows),
        "n_usable": len(usable),
        "n_truncated": sum(r["truncated"] for r in rows),
        "vgap_mean": _mean(means),
        "vgap_mean_stderr": _stderr(means),
        "vgap_mean_median": _percentile(means, 0.5),
        "vgap_mean_p25": _percentile(means, 0.25),
        "vgap_mean_p75": _percentile(means, 0.75),
        "vgap_sum": _mean(sums),
        "vgap_sum_median": _percentile(sums, 0.5),
        "response_tokens": _mean(lengths),
        "trace_accuracy": _mean([float(r["correct"]) for r in rows]),
        "quantiles": _quantile_grid(means),
        "report_quantiles": [_percentile(means, q) for q in REPORT_QUANTILES],
    }


def _ks_statistic(a: list[float], b: list[float]) -> float:
    """Largest vertical distance between two empirical CDFs.

    Summarizes how far apart the distributions are as wholes, rather than how
    far apart their centers are, so a shift that only moves part of the mass
    still registers.
    """
    if not a or not b:
        return float("nan")
    sorted_a, sorted_b = sorted(a), sorted(b)
    i = j = 0
    worst = 0.0
    while i < len(sorted_a) and j < len(sorted_b):
        x = min(sorted_a[i], sorted_b[j])
        while i < len(sorted_a) and sorted_a[i] <= x:
            i += 1
        while j < len(sorted_b) and sorted_b[j] <= x:
            j += 1
        worst = max(worst, abs(i / len(sorted_a) - j / len(sorted_b)))
    return worst


def _dominance(values: list[float], baseline: list[float]) -> str:
    """Whether one distribution sits wholly below or above the other.

    Comparing quantile functions pointwise is the same as comparing CDFs, so an
    answer of `below` means every quantile of v_gap fell: the defense moved the
    entire distribution, not just its average.
    """
    grid_a, grid_b = _quantile_grid(values), _quantile_grid(baseline)
    low = int(DOMINANCE_RANGE[0] * (len(GRID) - 1))
    high = int(DOMINANCE_RANGE[1] * (len(GRID) - 1))
    window = list(zip(grid_a[low : high + 1], grid_b[low : high + 1]))
    if not window:
        return "unknown"
    if all(a < b for a, b in window):
        return "below"
    if all(a > b for a, b in window):
        return "above"
    return "crosses"


def compare_to_baseline(
    rows: list[dict[str, Any]],
    baseline_rows: list[dict[str, Any]],
    drop_truncated: bool,
) -> dict[str, Any] | None:
    """Paired per-problem change in v_gap against the gamma = 0 traces.

    Only problems usable on both sides are paired, so a trace truncated in one
    condition cannot masquerade as a change in the gap.
    """
    baseline_by_id = {r["example_id"]: r for r in baseline_rows}
    deltas: list[float] = []
    delta_sums: list[float] = []
    paired_values: list[float] = []
    paired_baseline: list[float] = []
    for row in rows:
        base = baseline_by_id.get(row["example_id"])
        if base is None:
            continue
        if not (row["finite"] and base["finite"]):
            continue
        if drop_truncated and (row["truncated"] or base["truncated"]):
            continue
        deltas.append(row["vgap_mean"] - base["vgap_mean"])
        delta_sums.append(row["vgap_sum"] - base["vgap_sum"])
        paired_values.append(row["vgap_mean"])
        paired_baseline.append(base["vgap_mean"])
    if not deltas:
        return None

    mean_delta = _mean(deltas)
    stderr = _stderr(deltas)
    n_down = sum(1 for d in deltas if d < 0)
    return {
        "n_paired": len(deltas),
        "delta_mean": mean_delta,
        "delta_stderr": stderr,
        "delta_median": _percentile(deltas, 0.5),
        "delta_sum_mean": _mean(delta_sums),
        "frac_suppressed": n_down / len(deltas),
        "delta_quantiles": _quantile_grid(deltas),
        "delta_report_quantiles": [_percentile(deltas, q) for q in REPORT_QUANTILES],
        "ks_statistic": _ks_statistic(paired_values, paired_baseline),
        "dominance": _dominance(paired_values, paired_baseline),
        # How many standard errors the paired change sits from zero. With
        # thousands of pairs this is effectively a z statistic.
        "t_stat": mean_delta / stderr if stderr and math.isfinite(stderr) and stderr > 0 else float("nan"),
    }


def summarize_seed(traces: dict[str, list[dict[str, Any]]], drop_truncated: bool) -> dict[str, Any]:
    summary: dict[str, Any] = {}
    baseline_rows = traces.get(BASELINE)
    for source, rows in traces.items():
        entry = summarize_source(rows, drop_truncated)
        entry["gamma"] = _gamma_of(source)
        entry["defense"], entry["knob"], entry["strength"] = _defense_of(source)
        if baseline_rows is not None and source != BASELINE:
            entry["vs_baseline"] = compare_to_baseline(rows, baseline_rows, drop_truncated)
        summary[source] = entry
    return summary


def _fmt(value: Any, spec: str = ".4f") -> str:
    if value is None or (isinstance(value, float) and not math.isfinite(value)):
        return "-"
    return format(value, spec)


def pool_across_seeds(by_seed: dict[int, dict[str, Any]]) -> dict[str, Any]:
    """Average each statistic over seeds and record how far the seeds spread.

    The spread is a numerical-reproducibility check, not a confidence interval:
    teacher-forced scoring is deterministic and the seed only reshuffles batches.
    """
    sources: list[str] = []
    for summary in by_seed.values():
        for source in summary:
            if source not in sources:
                sources.append(source)

    pooled: dict[str, Any] = {}
    for source in sources:
        entries = [s[source] for s in by_seed.values() if source in s]
        base = dict(entries[0])
        for key in ("vgap_mean", "vgap_mean_median", "vgap_sum", "response_tokens"):
            values = [e[key] for e in entries if isinstance(e.get(key), float)]
            base[key] = _mean(values)
            base[f"{key}_seed_spread"] = (max(values) - min(values)) if len(values) > 1 else 0.0
        for key in ("quantiles", "report_quantiles"):
            grids = [e[key] for e in entries if e.get(key)]
            if grids:
                base[key] = [_mean(list(point)) for point in zip(*grids)]
        comparisons = [e["vs_baseline"] for e in entries if e.get("vs_baseline")]
        if comparisons:
            merged = dict(comparisons[0])
            for key in ("delta_mean", "delta_median", "frac_suppressed", "delta_sum_mean",
                        "t_stat", "ks_statistic"):
                values = [c[key] for c in comparisons if isinstance(c.get(key), float)]
                merged[key] = _mean(values)
                merged[f"{key}_seed_spread"] = (max(values) - min(values)) if len(values) > 1 else 0.0
            for key in ("delta_quantiles", "delta_report_quantiles"):
                grids = [c[key] for c in comparisons if c.get(key)]
                if grids:
                    merged[key] = [_mean(list(point)) for point in zip(*grids)]
            verdicts = {c.get("dominance") for c in comparisons}
            merged["dominance"] = verdicts.pop() if len(verdicts) == 1 else "crosses"
            base["vs_baseline"] = merged
        base["n_seeds"] = len(entries)
        pooled[source] = base
    return pooled


def _exclusion_warnings(
    pooled: dict[str, Any],
    order: list[str],
    drop_truncated: bool,
) -> list[str]:
    """Say so loudly when a source lost enough traces to distort its average."""
    empty = [s for s in order if pooled[s]["n_usable"] == 0]
    if empty:
        return [
            f"> **No usable traces for {', '.join(f'`{s}`' for s in empty)}, so their "
            "numbers are blank.** Every trace was either truncated at the length cap "
            "or scored non-finite. Raise `--max-length`, or pass `--keep-truncated` to "
            "score the kept prefix of each trace instead.",
            "",
        ]
    heavy = [s for s in order if (pooled[s]["n"] - pooled[s]["n_usable"]) / max(pooled[s]["n"], 1) > 0.05]
    if heavy and drop_truncated:
        return [
            "> **"
            + ", ".join(f"`{s}` lost {(pooled[s]['n'] - pooled[s]['n_usable']) / max(pooled[s]['n'], 1):.0%}"
                        for s in heavy)
            + " of its traces to the length cap.** Long traces are dropped, and length "
            "is related to the gap, so these averages are taken over a non-random subset. "
            "The paired comparison is unaffected in direction, since it only uses problems "
            "usable on both sides, but raise `--max-length` before quoting the levels.",
            "",
        ]
    return []


def _distribution_notes(pooled: dict[str, Any], order: list[str]) -> list[str]:
    """Turn the dominance and KS numbers into a sentence about each defense."""
    lines: list[str] = []
    for source in order:
        comparison = pooled[source].get("vs_baseline")
        if not comparison:
            continue
        ks = comparison.get("ks_statistic")
        # A uniform shift can still be a negligible one, so the size of the
        # separation is reported next to its direction, never on its own.
        big = isinstance(ks, float) and math.isfinite(ks) and ks >= 0.10
        if comparison["dominance"] == "below":
            if big:
                lines.append(
                    f"- `{source}`: every quantile from p01 to p99 sits below the "
                    "undefended teacher, so the defense moved the whole distribution "
                    "rather than pulling down a tail, and the two distributions are "
                    f"well separated (largest CDF gap {_fmt(ks, '.2f')})."
                )
            else:
                lines.append(
                    f"- `{source}`: every quantile sits below the undefended teacher, but "
                    f"only barely; the largest CDF gap is {_fmt(ks, '.2f')}, so the two "
                    "distributions almost entirely overlap. The direction is consistent, "
                    "the size is small."
                )
        elif comparison["dominance"] == "above":
            lines.append(
                f"- `{source}`: every quantile sits *above* the undefended teacher, so the "
                f"gap went up across the board (largest CDF gap {_fmt(ks, '.2f')})."
            )
        else:
            lines.append(
                f"- `{source}`: the two distributions cross, so the change is not uniform; "
                "some traces moved one way and some the other. Read the median change "
                f"rather than the mean (largest CDF gap {_fmt(ks, '.2f')})."
            )
    if lines:
        lines.append("")
    return lines


def _plot_label(source: str, entry: dict[str, Any]) -> str:
    defense = entry.get("defense", "other")
    strength = entry.get("strength")
    if defense == "none":
        return "undefended teacher"
    if strength is None:
        return source
    return f"{defense} {entry.get('knob', 'setting')} = {strength:g}"


def write_plot(pooled: dict[str, Any], path: Path) -> bool:
    """Two CDFs: the per-trace v_gap at each gamma, and the paired change.

    The left panel answers whether the distributions separate at all; the right
    answers how many problems moved and by how much, with everything left of
    zero being a problem whose gap the defense suppressed.
    """
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        return False

    order = _order_sources(pooled)
    colors = ["#222222", "#3b76af", "#8c4bbe", "#dd8452", "#c44e52", "#55a868", "#4f9d76"]
    fig, axes = plt.subplots(1, 2, figsize=(13.0, 5.2))

    for index, source in enumerate(order):
        entry = pooled[source]
        grid = entry.get("quantiles")
        if not grid:
            continue
        is_poe = entry.get("defense") in ("PoE", "none")
        axes[0].plot(
            grid,
            GRID,
            color=colors[index % len(colors)],
            linewidth=2.0 if is_poe else 1.6,
            linestyle="-" if is_poe else "--",
            label=_plot_label(source, entry),
        )
    axes[0].set_xlabel("per-trace v_gap per response token")
    axes[0].set_ylabel("fraction of traces at or below")
    axes[0].set_title(
        "Distribution of v_gap by defense\ncurves further left = gap more suppressed",
        fontsize=11,
    )

    for index, source in enumerate(order):
        entry = pooled[source]
        comparison = entry.get("vs_baseline")
        if not comparison or not comparison.get("delta_quantiles"):
            continue
        is_poe = entry.get("defense") == "PoE"
        axes[1].plot(
            comparison["delta_quantiles"],
            GRID,
            color=colors[index % len(colors)],
            linewidth=2.0 if is_poe else 1.6,
            linestyle="-" if is_poe else "--",
            label=_plot_label(source, entry),
        )
    axes[1].axvline(0.0, color="#888888", linewidth=1.0, linestyle=":")
    axes[1].set_xlabel("change in v_gap per token vs the same problem, undefended")
    axes[1].set_ylabel("fraction of problems at or below")
    axes[1].set_title(
        "Per-problem change\nmass left of the dotted line = suppressed",
        fontsize=11,
    )

    for ax in axes:
        ax.grid(True, alpha=0.22)
        ax.set_ylim(0, 1)
        ax.spines["top"].set_visible(False)
        ax.spines["right"].set_visible(False)
        ax.legend(frameon=False, fontsize=9, loc="best")

    fig.suptitle(
        "Do the token-level defenses suppress the teacher-proxy likelihood gap?",
        fontsize=13,
        y=1.02,
    )
    fig.tight_layout()
    fig.savefig(path, dpi=200, bbox_inches="tight")
    plt.close(fig)
    return True


def _order_sources(pooled: dict[str, Any]) -> list[str]:
    known = [s for s in PREFERRED_ORDER if s in pooled]
    return known + [s for s in pooled if s not in known]


def _strength(entry: dict[str, Any]) -> str:
    """The defense's knob and value, e.g. `gamma 0.60`, for a table cell."""
    strength = entry.get("strength")
    if entry.get("defense") == "none":
        return "-"
    if strength is None:
        return "?"
    return f"{entry.get('knob', 'setting')} {strength:g}"


def format_report(
    pooled: dict[str, Any],
    *,
    seeds: list[int],
    cfg: FullConfig,
    input_dir: Path,
    max_length: int,
    drop_truncated: bool,
    plot_name: str | None = None,
) -> str:
    order = _order_sources(pooled)
    baseline = pooled.get(BASELINE, {})
    lines = [
        "# Do the token-level defenses suppress the teacher-proxy likelihood gap?",
        "",
        f"Generated {datetime.now().strftime('%Y-%m-%d %H:%M')} from traces in `{input_dir}`.",
        "",
        f"- Teacher: `{cfg.model.teacher}`",
        f"- Proxy: `{cfg.model.proxy_student}`",
        f"- Seeds: {', '.join(str(s) for s in seeds)}",
        f"- Scored length cap: {max_length} tokens"
        + (", truncated traces excluded" if drop_truncated else ""),
        "",
        "The sequence-level rule these defenses are up against scores a whole "
        "trace with `v_gap(y) = log P_teacher(y) - log P_proxy(y)`. PoE samples "
        "each token from `p_teacher^(1-gamma) * p_proxy^gamma`, so it should steer "
        "the text toward tokens the proxy also finds likely and v_gap should fall "
        "as gamma rises. Antidistillation sampling is measured the same way at each "
        "lambda. No traces were regenerated; these are the same files the students "
        "train on.",
        "",
        "v_gap is one number per trace. It is reported divided by the trace's "
        "response tokens, because the raw sum grows with length and the defenses "
        "change length as a side effect, so a bare sum would partly be reporting "
        "how long the traces are. The summed form is in a table further down.",
        "",
        *(
            [f"![v_gap distributions]({plot_name})", ""]
            if plot_name
            else []
        ),
        "## Per-token v_gap by defense",
        "",
        "| source | defense | strength | traces | excluded | resp. tokens | mean v_gap/token | s.e. | median | IQR | trace acc |",
        "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for source in order:
        entry = pooled[source]
        excluded = entry["n"] - entry["n_usable"]
        lines.append(
            "| " + " | ".join([
                f"`{source}`",
                entry.get("defense", "?"),
                _strength(entry),
                str(entry["n_usable"]),
                f"{excluded} ({excluded / max(entry['n'], 1):.1%})",
                _fmt(entry["response_tokens"], ".0f"),
                _fmt(entry["vgap_mean"]),
                _fmt(entry["vgap_mean_stderr"]),
                _fmt(entry["vgap_mean_median"]),
                f"{_fmt(entry['vgap_mean_p25'], '.3f')} to {_fmt(entry['vgap_mean_p75'], '.3f')}",
                _fmt(entry["trace_accuracy"], ".3f"),
            ]) + " |"
        )

    lines += ["", *_exclusion_warnings(pooled, order, drop_truncated)]
    lines += [
        "Both defenses are measured here. PoE mixes the proxy into the sampling "
        "distribution, so it acts on v_gap directly and is the one the hypothesis "
        "is about. Antidistillation sampling perturbs the teacher's logits with a "
        "finite-difference penalty and never consults the proxy, so anything it "
        "does to v_gap is a side effect of changing the traces. Reading them "
        "together separates the two: a drop that appears under PoE but not under "
        "ADS is attributable to the proxy mixing rather than to perturbation in "
        "general, and a drop under ADS is worth knowing on its own, since it means "
        "a defense that never targets v_gap still moves it.",
        "",
        "## Change against the undefended teacher, paired by problem",
        "",
        "Every source covers the same GSM8K problems, so each trace is compared "
        "with the standard trace for the same problem and the differences are "
        "averaged. Pairing removes problem difficulty, which otherwise dominates "
        "the variation in v_gap. `suppressed` is the fraction of problems whose "
        "per-token gap went down at all, which assumes nothing about the shape "
        "of the distribution.",
        "",
        "| source | defense | strength | pairs | change in v_gap/token | s.e. | relative | median change | suppressed | s.e. from 0 |",
        "| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    base_mean = baseline.get("vgap_mean")
    for source in order:
        if source == BASELINE:
            continue
        comparison = pooled[source].get("vs_baseline")
        if not comparison:
            continue
        relative = (
            comparison["delta_mean"] / base_mean
            if isinstance(base_mean, float) and base_mean
            else float("nan")
        )
        lines.append(
            "| " + " | ".join([
                f"`{source}`",
                pooled[source].get("defense", "?"),
                _strength(pooled[source]),
                str(comparison["n_paired"]),
                _fmt(comparison["delta_mean"], "+.4f"),
                _fmt(comparison["delta_stderr"]),
                _fmt(relative, "+.1%"),
                _fmt(comparison["delta_median"], "+.4f"),
                _fmt(comparison["frac_suppressed"], ".1%"),
                _fmt(comparison["t_stat"], "+.1f"),
            ]) + " |"
        )

    lines += [
        "",
        "## The whole distribution, not just its average",
        "",
        "An average can move because every trace moved a little or because a few "
        "moved a lot, and those mean different things about the defense. These are "
        "the quantiles of the per-trace v_gap per token, which is the CDF read "
        "sideways: the p05 column is the value below which 5% of traces fall.",
        "",
        "| source | p05 | p10 | p25 | median | p75 | p90 | p95 | vs undefended |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | --- |",
    ]
    dominance_note = {
        "below": "every quantile lower",
        "above": "every quantile higher",
        "crosses": "curves cross",
        "unknown": "-",
    }
    for source in order:
        entry = pooled[source]
        quantiles = entry.get("report_quantiles") or []
        comparison = entry.get("vs_baseline")
        verdict = dominance_note.get(comparison["dominance"], "-") if comparison else "baseline"
        lines.append(
            "| " + " | ".join(
                [f"`{source}`"]
                + [_fmt(q, ".3f") for q in quantiles]
                + [verdict]
            ) + " |"
        )
    lines += ["", *_distribution_notes(pooled, order)]

    lines += [
        "## Summed v_gap, for reference",
        "",
        "This is the quantity as the sequence-level rule literally writes it, "
        "with no length normalization. Read the change here together with the "
        "response-token column: if a source's traces got shorter, its summed gap "
        "falls even when the per-token gap does not.",
        "",
        "| source | mean v_gap (summed) | median | resp. tokens | change vs undefended |",
        "| --- | ---: | ---: | ---: | ---: |",
    ]
    for source in order:
        entry = pooled[source]
        comparison = entry.get("vs_baseline")
        lines.append(
            "| " + " | ".join([
                f"`{source}`",
                _fmt(entry["vgap_sum"], ".1f"),
                _fmt(entry["vgap_sum_median"], ".1f"),
                _fmt(entry["response_tokens"], ".0f"),
                _fmt(comparison["delta_sum_mean"], "+.1f") if comparison else "-",
            ]) + " |"
        )

    lines += ["", "## Reading this", ""]
    lines += _verdict(pooled, order)
    lines += [
        "",
        "## On the seeds",
        "",
        f"Scored under {len(seeds)} seeds ({', '.join(str(s) for s in seeds)}). "
        "Teacher-forced scoring is deterministic: the traces are fixed and no "
        "sampling happens, so a seed cannot change the measured gap. Here it "
        "only reshuffles which traces share a batch, which changes padding and "
        "the order of floating-point reductions. The spread across seeds is "
        "therefore a numerical-stability check and should be near zero; the real "
        "uncertainty on each number is the s.e. across traces, and on each change "
        "the paired s.e.",
        "",
        "| source | v_gap/token spread across seeds | paired change spread |",
        "| --- | ---: | ---: |",
    ]
    for source in order:
        entry = pooled[source]
        comparison = entry.get("vs_baseline")
        lines.append(
            f"| `{source}` | {_fmt(entry.get('vgap_mean_seed_spread'), '.2e')} | "
            + (f"{_fmt(comparison.get('delta_mean_seed_spread'), '.2e')} |" if comparison else "- |")
        )
    lines.append("")
    return "\n".join(lines)


def _family_verdict(family: str, members: list[tuple[str, dict[str, Any]]]) -> list[str]:
    """What the numbers say about one defense family."""
    knob = members[0][1].get("knob", "setting")
    lines: list[str] = []

    suppressed = [s for s, e in members if e["vs_baseline"]["delta_mean"] < 0]
    if len(suppressed) == len(members):
        lines.append(
            f"- Every {family} setting lowers the per-token v_gap relative to the "
            "undefended teacher."
            + (" That is the direction the defense intends." if family == "PoE" else "")
        )
    elif suppressed:
        lines.append(
            f"- {len(suppressed)} of {len(members)} {family} settings lower the "
            "per-token v_gap; the rest do not, so the effect is not consistent."
        )
    else:
        lines.append(
            f"- **No {family} setting lowers the per-token v_gap.**"
            + (
                " The token-level implementation is not suppressing the quantity "
                "the sequence-level rule scores, which is the opposite of what it "
                "is meant to do."
                if family == "PoE"
                else ""
            )
        )

    ranked = sorted(
        (m for m in members if m[1].get("strength") is not None),
        key=lambda item: item[1]["strength"],
    )
    if len(ranked) >= 2:
        deltas = [e["vs_baseline"]["delta_mean"] for _, e in ranked]
        if all(b <= a for a, b in zip(deltas, deltas[1:])):
            lines.append(
                f"- The effect grows with {knob}: a stronger setting suppresses the "
                "gap further."
                + (" That is what the mechanism predicts." if family == "PoE" else "")
            )
        else:
            lines.append(
                f"- The effect does not grow monotonically with {knob}, so over this "
                "range a stronger setting does not reliably suppress the gap further."
            )

    finite = [abs(e["vs_baseline"]["t_stat"]) for _, e in members
              if math.isfinite(e["vs_baseline"]["t_stat"])]
    if finite:
        weakest = min(finite)
        if weakest >= 3:
            lines.append(
                f"- The weakest {family} change still sits {weakest:.0f} standard "
                "errors from zero, so none of them is a sampling artifact."
            )
        else:
            lines.append(
                f"- The weakest {family} change sits only {weakest:.1f} standard errors "
                "from zero, so at least one of these differences is within noise."
            )
    return lines


def _verdict(pooled: dict[str, Any], order: list[str]) -> list[str]:
    """State what the numbers say about each defense, in plain terms."""
    families: dict[str, list[tuple[str, dict[str, Any]]]] = {}
    for source in order:
        entry = pooled[source]
        if source == BASELINE or not entry.get("vs_baseline"):
            continue
        families.setdefault(entry.get("defense", "other"), []).append((source, entry))

    if not families:
        return ["No defended sources were scored, so there is nothing to conclude."]

    lines: list[str] = []
    for family in sorted(families, key=lambda f: (f != "PoE", f)):
        lines += _family_verdict(family, families[family])

    poe = families.get("PoE")
    controls = [m for f, members in families.items() if f != "PoE" for m in members]
    if poe and controls:
        poe_shift = _mean([abs(e["vs_baseline"]["delta_mean"]) for _, e in poe])
        control_shift = _mean([abs(e["vs_baseline"]["delta_mean"]) for _, e in controls])
        if control_shift and poe_shift > 2 * control_shift:
            lines.append(
                f"- PoE moves the gap {poe_shift / control_shift:.1f}x further than the "
                "defenses that never consult the proxy, so the effect tracks the proxy "
                "mixing rather than trace perturbation in general."
            )
        elif control_shift >= poe_shift:
            lines.append(
                "- The defenses that never consult the proxy move the gap as much as PoE "
                "does. That undercuts attributing the change to the proxy mixing; "
                "something common to both is moving it."
            )
    return lines


def load_seed_files(output_dir: Path) -> dict[int, dict[str, Any]]:
    found: dict[int, dict[str, Any]] = {}
    for path in sorted(output_dir.glob("seed_*/summary.json")):
        seed = int(path.parent.name.removeprefix("seed_"))
        found[seed] = json.loads(path.read_text())["sources"]
    return found


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument("--input-dir", default="gsm8k_output_small", help="Saved-trace directory.")
    parser.add_argument(
        "--sources",
        nargs="*",
        default=None,
        help="Trace stems to score. Defaults to every train_*.json in the input directory.",
    )
    parser.add_argument("--config", default="configs/gsm8k.yaml", help="Run config naming teacher and proxy.")
    parser.add_argument("--output-dir", default="outputs/vgap_poe", help="Where results and the report go.")
    parser.add_argument("--seed", default=123, type=int, help="Batch-composition seed; see the report.")
    parser.add_argument(
        "--batch-size",
        default=None,
        type=int,
        help=(
            "Sequences per forward pass. Defaults to the config's "
            "distill.trace_weights_fd_batch_size, which is its setting for this same "
            "operation: a no-grad forward followed by a full-vocabulary log-prob gather."
        ),
    )
    parser.add_argument(
        "--row-chunk",
        default=1024,
        type=int,
        help="Token positions softmaxed at once in fp32. Lower this first if scoring OOMs.",
    )
    parser.add_argument("--max-length", default=None, type=int, help="Defaults to distill.max_length.")
    parser.add_argument("--limit", default=0, type=int, help="Score only the first N traces, 0 for all.")
    parser.add_argument(
        "--keep-truncated",
        action="store_true",
        help=(
            "Include traces that hit the length cap. They are excluded by default "
            "because a cut-off trace's gap covers only the kept prefix."
        ),
    )
    parser.add_argument(
        "--report-only",
        action="store_true",
        help="Rebuild the report from seed results already on disk, loading no models.",
    )
    args = parser.parse_args()

    input_dir = Path(args.input_dir)
    output_dir = Path(args.output_dir)
    cfg = FullConfig.from_yaml(Path(args.config))
    if cfg.model.proxy_student is None:
        raise ValueError(f"{args.config} has no model.proxy_student, so v_gap is undefined")
    max_length = args.max_length or cfg.distill.max_length
    drop_truncated = not args.keep_truncated
    # generation.batch_size (240) is for sampling, where only one column of
    # logits is live at a time. Scoring materializes (batch, seq, vocab), so it
    # needs the config's forward-pass batch size instead.
    batch_size = args.batch_size or cfg.distill.trace_weights_fd_batch_size

    sources = args.sources or discover_sources(input_dir)
    if BASELINE not in sources:
        raise ValueError(
            f"`{BASELINE}` must be among the sources; it is the gamma = 0 baseline "
            "every other source is compared against."
        )
    for source in sources:
        path = input_dir / f"train_{source}.json"
        if not path.exists():
            raise FileNotFoundError(f"No such trace file: {path}")

    from clean_sweep.utils import ensure_dir, write_json

    if not args.report_only:
        console.rule(f"v_gap by gamma | seed {args.seed}")
        console.print(f"  Teacher:    {cfg.model.teacher}")
        console.print(f"  Proxy:      {cfg.model.proxy_student}")
        console.print(
            f"  Batch size: {batch_size}"
            + ("" if args.batch_size else " (from config distill.trace_weights_fd_batch_size)")
        )
        console.print(f"  Sources:    {', '.join(sources)}\n")

        scored = score_sources(
            sources,
            input_dir,
            cfg,
            max_length=max_length,
            batch_size=batch_size,
            row_chunk=args.row_chunk,
            seed=args.seed,
            limit=args.limit,
        )
        if any(scored["clamped"].values()):
            console.print(
                f"  [yellow]Clamped out-of-vocabulary ids: {scored['clamped']}. "
                "Those tokens' log-probs are meaningless.[/yellow]"
            )

        summary = summarize_seed(scored["traces"], drop_truncated)
        seed_dir = ensure_dir(output_dir / f"seed_{args.seed}")
        write_json(scored["traces"], seed_dir / "per_trace.json")
        write_json(
            {
                "seed": args.seed,
                "input_dir": str(input_dir),
                "teacher": cfg.model.teacher,
                "proxy": cfg.model.proxy_student,
                "max_length": max_length,
                "batch_size": batch_size,
                "drop_truncated": drop_truncated,
                "clamped_ids": scored["clamped"],
                "definition": (
                    "vgap(y) = log P_teacher(y) - log P_proxy(y) over response tokens, "
                    "both on teacher-tokenized ids; vgap_mean divides by response tokens"
                ),
                "created_at": datetime.now().isoformat(),
                "sources": summary,
            },
            seed_dir / "summary.json",
        )
        console.print(f"\n  Wrote {seed_dir}")

    by_seed = load_seed_files(output_dir)
    if not by_seed:
        console.print(f"[yellow]No seed results under {output_dir}. Nothing to report.[/yellow]")
        return

    pooled = pool_across_seeds(by_seed)
    ensure_dir(output_dir)
    plot_path = output_dir / "vgap_cdf.png"
    has_plot = write_plot(pooled, plot_path)
    if not has_plot:
        console.print("  [yellow]matplotlib is missing, so no CDF plot was drawn.[/yellow]")
    report = format_report(
        pooled,
        seeds=sorted(by_seed),
        cfg=cfg,
        input_dir=input_dir,
        max_length=max_length,
        drop_truncated=drop_truncated,
        plot_name=plot_path.name if has_plot else None,
    )
    # Written last and in one shot: several array tasks may reach this point at
    # once, and a partial file is worse than a stale one.
    tmp = output_dir / "RESULTS.md.partial"
    tmp.write_text(report)
    tmp.replace(output_dir / "RESULTS.md")
    write_json(pooled, output_dir / "pooled.json")

    console.rule("Average v_gap per response token")
    for source in _order_sources(pooled):
        entry = pooled[source]
        excluded = entry["n"] - entry["n_usable"]
        if excluded / max(entry["n"], 1) > 0.05:
            console.print(
                f"  [yellow]{source}: {excluded}/{entry['n']} traces excluded "
                "(truncated at the length cap or non-finite).[/yellow]"
            )
        label = (
            "undefended"
            if entry.get("defense") == "none"
            else f"{entry.get('defense', '?')} {_strength(entry)}"
        )
        line = (
            f"  {source:30s} {label:>18s}  "
            f"mean {entry['vgap_mean']:+.4f} +/- {entry['vgap_mean_stderr']:.4f}  "
            f"median {entry['vgap_mean_median']:+.4f}"
        )
        comparison = entry.get("vs_baseline")
        if comparison:
            line += (
                f"   change {comparison['delta_mean']:+.4f} "
                f"({comparison['frac_suppressed']:.0%} of problems down, "
                f"{comparison['dominance']})"
            )
        console.print(line)
    console.print(f"\n  Wrote {output_dir / 'RESULTS.md'} from seeds {sorted(by_seed)}")


if __name__ == "__main__":
    main()
